---
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      version_increment_type: ${{ steps.get_version_increment_type.outputs.version_increment_type }}
    steps:
      - uses: actions/checkout@v3
      - id: get_version_increment_type
        name: Get version increment type
        run: |
          set -euo pipefail

          version_increment_type="none"
          if [[ "${{ github.event.head_commit.message }}" =~ (major|minor|patch)([^,]*) ]]; then
            version_increment_type="${BASH_REMATCH[1]}"
          fi
          echo "Version increment type: ${version_increment_type}"
          echo "version_increment_type=$version_increment_type" >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: make build
      - run: make test
      - name: Configure git
        run: |
          git config --global url."https://x-oauth-basic:${{ secrets.GITHUB_TOKEN }}@github.com/frontierdigital".insteadOf https://github.com/frontierdigital
      - id: increment_version
        if: needs.preflight.outputs.version_increment_type != 'none'
        uses: reecetech/version-increment@2023.4.1
        with:
          scheme: semver
          increment: ${{ needs.preflight.outputs.version_increment_type }}
      - name: Add version tag
        if: steps.increment_version.outcome == 'success'
        run: |
          set -euo pipefail

          git config --global user.email "bot@frontierdigital.net"
          git config --global user.name "Frontier Digital Bot"

          git tag -a "${{ steps.increment_version.outputs.v-version }}" -m "${{ steps.increment_version.outputs.v-version }}"
          git push origin "${{ steps.increment_version.outputs.v-version }}"
